"""
Evidence-backed activity database for the Dopamine Menu Generator.
Each activity is tagged with mood affinities, energy requirements,
time needs, and psychological benefit scores grounded in positive
psychology research (Seligman, Csikszentmihalyi, Fredrickson, et al.).
"""

ACTIVITIES = [
    # ── MOVEMENT ──────────────────────────────────────────────────────────────
    {
        "id": "walk_nature",
        "name": "Walk in a natural setting",
        "emoji": "🌿",
        "category": "Movement",
        "min_time": 20,
        "energy": "low",
        "moods": ["anxious", "sad", "numb", "overwhelmed", "restless"],
        "benefit_score": 9.2,
        "mechanism": "Awe induction + attention restoration theory",
        "research_note": "Nature walks reduce rumination and subgenual prefrontal cortex activity (Bratman et al., 2015).",
        "tip": "Leave your phone in your pocket for the first 10 minutes.",
    },
    {
        "id": "dance_alone",
        "name": "Dance alone in your room",
        "emoji": "🕺",
        "category": "Movement",
        "min_time": 5,
        "energy": "medium",
        "moods": ["sad", "numb", "anxious", "bored", "restless"],
        "benefit_score": 8.7,
        "mechanism": "Embodied emotion regulation + endorphin release",
        "research_note": "Self-directed movement to music improves affect more than passive music listening (Koch et al., 2019).",
        "tip": "Pick one song that felt important to a younger version of you.",
    },
    {
        "id": "yoga_gentle",
        "name": "Gentle yoga or stretching",
        "emoji": "🧘",
        "category": "Movement",
        "min_time": 10,
        "energy": "low",
        "moods": ["anxious", "overwhelmed", "exhausted", "tense"],
        "benefit_score": 8.4,
        "mechanism": "Vagal nerve activation + interoceptive awareness",
        "research_note": "Even brief yoga reduces cortisol and increases GABA (Streeter et al., 2010).",
        "tip": "Focus on exhales being twice as long as inhales.",
    },
    {
        "id": "run_sprint",
        "name": "Short high-intensity run or sprint",
        "emoji": "🏃",
        "category": "Movement",
        "min_time": 15,
        "energy": "high",
        "moods": ["anxious", "angry", "restless", "sad"],
        "benefit_score": 9.0,
        "mechanism": "BDNF release + norepinephrine regulation",
        "research_note": "Aerobic exercise is as effective as antidepressants for mild-moderate depression (Blumenthal et al., 1999).",
        "tip": "Run until you're too out of breath to think about whatever's bothering you.",
    },
    {
        "id": "cold_shower",
        "name": "Cold shower (30–90 seconds)",
        "emoji": "🚿",
        "category": "Movement",
        "min_time": 5,
        "energy": "medium",
        "moods": ["numb", "exhausted", "sad", "bored"],
        "benefit_score": 7.8,
        "mechanism": "Norepinephrine spike + shock-induced alertness",
        "research_note": "Cold exposure increases norepinephrine by 200–300% (Šrámek et al., 2000).",
        "tip": "Start warm, end cold. Even 30 seconds counts.",
    },

    # ── CREATIVE ──────────────────────────────────────────────────────────────
    {
        "id": "journal_free",
        "name": "Freewrite in a journal (no editing)",
        "emoji": "📓",
        "category": "Creative",
        "min_time": 10,
        "energy": "low",
        "moods": ["overwhelmed", "anxious", "sad", "confused", "numb"],
        "benefit_score": 8.9,
        "mechanism": "Expressive writing + cognitive processing",
        "research_note": "Pennebaker's expressive writing protocol reduces depression, anxiety, and doctor visits over time.",
        "tip": "Write 'I don't know what to write' until something real comes out.",
    },
    {
        "id": "draw_doodle",
        "name": "Draw or doodle with no goal",
        "emoji": "✏️",
        "category": "Creative",
        "min_time": 10,
        "energy": "low",
        "moods": ["anxious", "bored", "overwhelmed", "restless", "numb"],
        "benefit_score": 7.6,
        "mechanism": "Default mode network quieting + flow state entry",
        "research_note": "Unstructured art-making reduces cortisol in 75% of participants (Kaimal et al., 2016).",
        "tip": "Use your non-dominant hand if you feel self-critical about your drawing.",
    },
    {
        "id": "cook_new",
        "name": "Cook or bake something new",
        "emoji": "🍳",
        "category": "Creative",
        "min_time": 30,
        "energy": "medium",
        "moods": ["bored", "numb", "sad", "restless"],
        "benefit_score": 8.1,
        "mechanism": "Behavioral activation + sensory engagement + mastery",
        "research_note": "Everyday creativity correlates with next-day positive affect and flourishing (Conner et al., 2016).",
        "tip": "Pick a recipe with at least one ingredient you've never cooked with.",
    },
    {
        "id": "music_instrument",
        "name": "Play an instrument (even badly)",
        "emoji": "🎸",
        "category": "Creative",
        "min_time": 15,
        "energy": "low",
        "moods": ["sad", "numb", "anxious", "bored"],
        "benefit_score": 8.5,
        "mechanism": "Flow state induction + dopaminergic reward",
        "research_note": "Musical improvisation deactivates the prefrontal cortex, enabling freer self-expression (Limb & Braun, 2008).",
        "tip": "Don't practice. Just play.",
    },
    {
        "id": "rearrange_space",
        "name": "Rearrange or redecorate a small space",
        "emoji": "🪴",
        "category": "Creative",
        "min_time": 20,
        "energy": "medium",
        "moods": ["bored", "restless", "numb", "sad"],
        "benefit_score": 7.3,
        "mechanism": "Environmental agency + novelty-seeking reward",
        "research_note": "Environmental control is a core component of autonomy, a basic psychological need (Deci & Ryan, SDT).",
        "tip": "Move one plant or lamp. That's sometimes enough.",
    },

    # ── SOCIAL ────────────────────────────────────────────────────────────────
    {
        "id": "call_friend",
        "name": "Call (not text) a friend",
        "emoji": "📞",
        "category": "Social",
        "min_time": 15,
        "energy": "medium",
        "moods": ["sad", "lonely", "anxious", "numb"],
        "benefit_score": 9.4,
        "mechanism": "Oxytocin release + belonging need satisfaction",
        "research_note": "Phone calls reduce loneliness significantly more than texts (Sandstrom & Boothby, 2021).",
        "tip": "Say 'I just called to hear your voice' and mean it.",
    },
    {
        "id": "write_letter",
        "name": "Write a letter you may or may not send",
        "emoji": "✉️",
        "category": "Social",
        "min_time": 15,
        "energy": "low",
        "moods": ["sad", "angry", "lonely", "overwhelmed"],
        "benefit_score": 7.9,
        "mechanism": "Perspective-taking + emotional processing",
        "research_note": "Unsent letter writing is a validated grief and anger processing technique in clinical psychology.",
        "tip": "Write one to someone you miss, someone you're angry at, or your past self.",
    },
    {
        "id": "compliment_stranger",
        "name": "Give a genuine compliment to someone",
        "emoji": "💬",
        "category": "Social",
        "min_time": 2,
        "energy": "low",
        "moods": ["numb", "sad", "bored", "lonely"],
        "benefit_score": 8.0,
        "mechanism": "Prosocial behavior boost + warm glow effect",
        "research_note": "Compliment-giving increases giver's mood more than receivers realize (Boothby & Bohns, 2021).",
        "tip": "Make it specific: not 'you're smart' but 'the way you explained that helped me.'",
    },
    {
        "id": "shared_meal",
        "name": "Eat a meal with another person, slowly",
        "emoji": "🍽️",
        "category": "Social",
        "min_time": 30,
        "energy": "low",
        "moods": ["lonely", "numb", "sad", "anxious"],
        "benefit_score": 8.6,
        "mechanism": "Commensality bonding + parasympathetic activation",
        "research_note": "Commensality (shared eating) is one of the strongest predictors of wellbeing across cultures (Dunbar, 2017).",
        "tip": "No phones. Ask one question you actually want to know the answer to.",
    },

    # ── REST & RESTORATION ────────────────────────────────────────────────────
    {
        "id": "nap",
        "name": "Take a short nap (10–20 min)",
        "emoji": "😴",
        "category": "Rest",
        "min_time": 15,
        "energy": "low",
        "moods": ["exhausted", "overwhelmed", "numb", "sad"],
        "benefit_score": 8.2,
        "mechanism": "Sleep pressure relief + memory consolidation",
        "research_note": "A 10-minute nap improves alertness and mood for up to 2.5 hours (Lovato & Lack, 2010).",
        "tip": "Set an alarm for 20 minutes. Longer and you'll feel worse.",
    },
    {
        "id": "breathwork",
        "name": "Box breathing or 4-7-8 breathwork",
        "emoji": "🌬️",
        "category": "Rest",
        "min_time": 5,
        "energy": "low",
        "moods": ["anxious", "overwhelmed", "tense", "angry"],
        "benefit_score": 8.8,
        "mechanism": "Parasympathetic nervous system activation",
        "research_note": "Cyclic sighing outperforms mindfulness meditation for acute anxiety reduction (Balban et al., 2023).",
        "tip": "Inhale 4 counts, hold 7, exhale 8. Repeat 4 times. That's the whole thing.",
    },
    {
        "id": "bath_soak",
        "name": "Take a long bath or shower",
        "emoji": "🛁",
        "category": "Rest",
        "min_time": 20,
        "energy": "low",
        "moods": ["anxious", "tense", "sad", "exhausted", "overwhelmed"],
        "benefit_score": 7.7,
        "mechanism": "Thermally-induced vasodilation + sensory reset",
        "research_note": "Warm baths improve mood and reduce loneliness through thermosensory processing linked to social warmth (IJzerman & Semin, 2009).",
        "tip": "No podcast, no phone. Just hot water.",
    },
    {
        "id": "do_nothing",
        "name": "Do absolutely nothing for 10 minutes",
        "emoji": "☁️",
        "category": "Rest",
        "min_time": 10,
        "energy": "low",
        "moods": ["overwhelmed", "exhausted", "anxious", "numb"],
        "benefit_score": 7.5,
        "mechanism": "Default mode network restoration + mind-wandering benefits",
        "research_note": "Mind-wandering activates the default mode network, supporting creativity, future planning, and self-coherence (Smallwood & Schooler, 2015).",
        "tip": "Sit in a chair. Look at a wall or window. That's it. No phone.",
    },

    # ── LEARNING & MEANING ────────────────────────────────────────────────────
    {
        "id": "read_fiction",
        "name": "Read fiction for 20+ minutes",
        "emoji": "📚",
        "category": "Learning",
        "min_time": 20,
        "energy": "low",
        "moods": ["anxious", "bored", "sad", "numb", "lonely"],
        "benefit_score": 8.3,
        "mechanism": "Narrative transportation + empathy activation",
        "research_note": "Literary fiction reading increases theory of mind and reduces loneliness (Mar et al., 2009; Kidd & Castano, 2013).",
        "tip": "Start a chapter, not an article. Your phone will still be there.",
    },
    {
        "id": "learn_one_thing",
        "name": "Learn one random thing deeply",
        "emoji": "🔭",
        "category": "Learning",
        "min_time": 15,
        "energy": "medium",
        "moods": ["bored", "numb", "restless", "sad"],
        "benefit_score": 7.8,
        "mechanism": "Curiosity-driven dopamine + cognitive engagement",
        "research_note": "Curiosity activates the dopaminergic reward circuit and improves memory consolidation (Gruber et al., 2014).",
        "tip": "Pick literally anything — how locks work, why the sky is blue, the history of chewing gum.",
    },
    {
        "id": "gratitude_specific",
        "name": "Write 3 hyper-specific things you're grateful for",
        "emoji": "🙏",
        "category": "Meaning",
        "min_time": 5,
        "energy": "low",
        "moods": ["sad", "numb", "anxious", "overwhelmed"],
        "benefit_score": 8.6,
        "mechanism": "Positive emotion broadening + attention reorientation",
        "research_note": "Specific (not generic) gratitude journaling increases wellbeing and reduces hedonic adaptation (Emmons & McCullough, 2003).",
        "tip": "Not 'my health.' More like: 'The exact sound my coffee maker makes at 7am.'",
    },
    {
        "id": "help_someone",
        "name": "Do one small thing to help someone",
        "emoji": "🤝",
        "category": "Meaning",
        "min_time": 10,
        "energy": "medium",
        "moods": ["sad", "numb", "bored", "lonely"],
        "benefit_score": 9.1,
        "mechanism": "Helper's high + purpose activation",
        "research_note": "Prosocial spending and helping behavior produces larger wellbeing gains than self-directed rewards (Dunn et al., 2008).",
        "tip": "Text someone asking if they need anything. Actually mean it.",
    },
    {
        "id": "watch_sky",
        "name": "Watch the sky (sunrise, sunset, or clouds)",
        "emoji": "🌅",
        "category": "Meaning",
        "min_time": 5,
        "energy": "low",
        "moods": ["anxious", "sad", "overwhelmed", "numb", "restless"],
        "benefit_score": 8.0,
        "mechanism": "Awe induction + self-transcendence",
        "research_note": "Awe experiences reduce self-referential rumination and increase feelings of connection (Stellar et al., 2018).",
        "tip": "No filter, no photo. Just look.",
    },

    # ── SENSORY ───────────────────────────────────────────────────────────────
    {
        "id": "scent_reset",
        "name": "Use a scent intentionally (candle, essential oil, fresh air)",
        "emoji": "🕯️",
        "category": "Sensory",
        "min_time": 5,
        "energy": "low",
        "moods": ["numb", "anxious", "sad", "overwhelmed"],
        "benefit_score": 7.2,
        "mechanism": "Olfactory-limbic pathway + memory/emotion anchor",
        "research_note": "Olfaction has direct access to the amygdala and hippocampus, making it uniquely potent for mood shifting (Herz, 2009).",
        "tip": "Associate one scent with calm. Use it only for calm.",
    },
    {
        "id": "music_full_album",
        "name": "Listen to a full album without doing anything else",
        "emoji": "🎧",
        "category": "Sensory",
        "min_time": 35,
        "energy": "low",
        "moods": ["numb", "sad", "bored", "lonely"],
        "benefit_score": 8.1,
        "mechanism": "Deep listening + emotional resonance + nostalgia activation",
        "research_note": "Music-evoked nostalgia increases social connectedness and existential meaning (Sedikides et al., 2015).",
        "tip": "Pick something you loved at 17. Listen with your eyes closed.",
    },
    {
        "id": "eat_mindfully",
        "name": "Eat one thing very slowly and mindfully",
        "emoji": "🍊",
        "category": "Sensory",
        "min_time": 10,
        "energy": "low",
        "moods": ["anxious", "numb", "overwhelmed", "restless"],
        "benefit_score": 7.6,
        "mechanism": "Mindful eating + interoceptive grounding",
        "research_note": "Mindful eating reduces stress reactivity and emotional eating, while increasing meal satisfaction (O'Reilly et al., 2014).",
        "tip": "Peel an orange. Smell it before you eat it.",
    },
]

MOODS = [
    "anxious", "sad", "numb", "overwhelmed", "restless",
    "bored", "exhausted", "angry", "lonely", "tense", "confused"
]

ENERGY_LEVELS = ["low", "medium", "high"]

CATEGORIES = sorted(set(a["category"] for a in ACTIVITIES))
